name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      docker_username: 
        required: true
        type: string
      docker_password: 
        required: true
        type: string
      image_tag: 
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_password }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ inputs.image_tag }}
