name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  call-quality-checks:
    uses: ./.github/workflows/quality_checks.yml

  build:
    needs: call-quality-checks
    uses: ./.github/workflows/build_and_push.yml
    with:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      image_tag: bullder/checker:latest
