name: Quality Checks

on:
  workflow_call:

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: make setup
      - name: Run lint
        run: make lint
      - name: Run type-check
        run: make type-check
      - name: Run tests
        run: make test
      - name: Run coverage
        run: make coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov
